
name: download_from_wayback

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 */12 * * *"

jobs:
  download_from_wayback:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ghostscript
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build

    - name: Run workflows/download_from_wayback.py 
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python workflows/download_from_wayback.py 
    
    - name: Checkout repo branch data
      uses: actions/checkout@v2
      with:
        ref: 'data'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git pull origin data
        cp -r /tmp/weather_lk/* .
        echo "* download_from_wayback $(date)" >> update.log
        git add .
        git commit -m "🤖 $(date) - download_from_wayback.yml"
        git push origin data
